### ISSUE TITLE
That tutorial was integrated to ahk documentation. Does we need that repo?

### ISSUE THREAD

**Issue by vasili111** [ahkscript/AHK_Tutorial#3]
That tutorial was integrated to ahk documentation. ( http://ahkscript.org/boards/viewtopic.php?p=34879#p34879 ).
I think it is better to delete " ahkscript/AHK_Tutorial " repository and do all corrections and additions in ahk documentation repo.
What you think about it?

**Comment by dufferzafar** [comment]
Yeah, sounds about right.

**Comment by ErEXON** [comment]
+1.

**Comment by joedf** [comment]
Ok, I agree but i want to keep this repo for convenience. Say, I'll make a folder "Legacy Version" and put the files in there. And, I'll put a readme as a notice to users that don't know of this. Like a reminder or redirect. I will do this tomorrow night.
